### PR TITLE
Fix spawner functionality in 1.8, fixes #22 (and many more)

### LINKED ISSUE #22: Fix spawnerconvert functionaltity
Essentials supports the retrieval of premade mobspawners (/i mobspawner:mobdatavalue) and should usually, if the player has the permission for the specific mob, change the spawner on placement automatically to the given mobtype. Due to changes of data value handling in vanilla 1.8, it is no longer possible to store such value for mobspawners in the item while in inventory. Maybe add a lore and read that on placement?

### PR DESCRIPTION
**Pull request by vemacs**
This fixes:

* Spawner convert (#22)
* /give command with spawners
* sell signs with spawners

This degrades to legacy durability/data access on pre-1.8.3.

### CODE REVIEW

**Comment by vemacs** [comment]
Demonstration of /give command and placement: https://gfycat.com/KlutzyShadyBelugawhale

**Comment by vemacs** [comment]
@drtshock If this gets merge, you may want to advertise EssX by listing this as a feature on:

http://dev.bukkit.org/bukkit-plugins/silkspawners/
http://www.spigotmc.org/threads/essentials-spawners-in-1-8.37148/
http://www.spigotmc.org/threads/selling-spawners-in-1-8.67092/
http://www.spigotmc.org/threads/no-custom-mob-spawners-in-1-8.48856/

**Comment by Kakifrucht** [comment]
Nice man, thanks alot!

**Comment by drtshock** [comment]
Merged! Thanks @vemacs :)

**Comment by vemacs** [comment]
@drtshock Didn't merge the rest of the commits

**Comment by drtshock** [comment]
I squashed it.

**Comment by vemacs** [comment]
Ah, cool

**Pull request closed without merging**
